import {
    project1Laptop,
    project1Mobile,
    project2Laptop,
    project2Mobile,
    project3Laptop,
    project3Mobile,
    project4Laptop,
    project4Mobile,
    project5Laptop,
    project5Mobile,
    project6Laptop,
    project6Mobile,
} from "./projectImages";

export const projectData = [
    {
        id: 1,
        image: project1Laptop,
        transitionImage: project1Mobile,
        title: "React Portfolio Website",
        codeLink: "https://github.com/doniyortojikhonov",
        liveLink: "https://react-portfolio-website-01.netlify.app/",
    },
    {
        id: 2,
        image: project2Laptop,
        transitionImage: project2Mobile,
        title: "Project 1",
        codeLink: "https://github.com/doniyortojikhonov",
        liveLink: "",
    },
    {
        id: 3,
        image: project3Laptop,
        transitionImage: project3Mobile,
        title: "Project 2",
        codeLink: "https://github.com/doniyortojikhonov",
        liveLink: "",
    },
    {
        id: 4,
        image: project4Laptop,
        transitionImage: project4Mobile,
        title: "Project 3",
        codeLink: "https://github.com/doniyortojikhonov",
        liveLink: "",
    },
    {
        id: 5,
        image: project5Laptop,
        transitionImage: project5Mobile,
        title: "Project 4",
        codeLink: "https://github.com/doniyortojikhonov",
        liveLink: "",
    },
    {
        id: 6,
        image: project6Laptop,
        transitionImage: project6Mobile,
        title: "Project 5",
        codeLink: "https://github.com/doniyortojikhonov",
        liveLink: "",
    },
];
